version: '3.8'

services:
  glean-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: glean-mcp-server-dev
    environment:
      - GLEAN_BASE_URL=${GLEAN_BASE_URL}
      - GLEAN_COOKIES=${GLEAN_COOKIES}
      - LOG_LEVEL=${LOG_LEVEL:-DEBUG}
    volumes:
      # Mount source code for development
      - ./src:/app/src:ro
    restart: unless-stopped
    stdin_open: true
    tty: true

networks:
  glean-network:
    driver: bridge
