version: '3.8'

services:
  glean-mcp-server:
    # Use pre-built image from GitHub Container Registry
    # Comment out the 'image' line and uncomment 'build' section for local development
    image: ghcr.io/alankyshum/glean-mcp-server:latest

    # Uncomment for local development:
    # build:
    #   context: .
    #   dockerfile: Dockerfile

    container_name: glean-mcp-server
    environment:
      - GLEAN_BASE_URL=${GLEAN_BASE_URL}
      - GLEAN_COOKIES=${GLEAN_COOKIES}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    restart: unless-stopped
    stdin_open: true
    tty: true

networks:
  glean-network:
    driver: bridge
