version: '3.8'

services:
  glean-mcp-server:
    image: ghcr.io/alankyshum/glean-mcp-server:latest
    container_name: glean-mcp-server
    environment:
      - GLEAN_BASE_URL=${GLEAN_BASE_URL}
      - GLEAN_COOKIES=${GLEAN_COOKIES}
    restart: unless-stopped
    stdin_open: true
    tty: true
